'use strict';function status(a){$$("[name=status]").innerText=a}function popup_msg(a,b){var c=$$("[name=popup_msg]");a=a.getBoundingClientRect();c.innerText=b;c.style.top=5+a.top+"px";c.style.left=a.left+"px";c.style.display="";setTimeout(()=>{c.style.display="none"},3E3)}
function magicpacket(a,b){var c=new ArrayBuffer(114),d=new Uint8Array(c),e,f,g=0;for(e=0;6>e;++e)d[g+e]=255;g+=6;for(e=0;6>e;++e)for(f=0;96>f;f+=6)d[g+f+e]=a[e];g+=96;for(e=0;6>e;++e)d[g+e]=255;g+=6;for(e=0;6>e;++e)d[g+e]=b[e];return c}
function split_data(a){var b=Array(6),c;window["sync_"+a]();for(c=0;6>c;++c){var d=$$("input[name="+a+c+"]");if(!/^[0-9a-fA-F]?[0-9a-fA-F]$/.test(d.value.replace(" ","")))return status(a+" byte "+c+" is invalid; must be 2 hex characters"),d.focus(),d.setSelectionRange(0,d.value.length),!1;b[c]=parseInt(d.value,16)}return b}
function send(){status("initializing");var a=$$("form[name=settings]"),b=a.host.value,c=parseInt(a.port.value);a=split_data("mac");var d=split_data("pass"),e=magicpacket(a,d);console.log("packet",new Uint8Array(e));var f=function(a,b,c){return 0>c?(status("error in "+b+": "+net_error_list[c]),chrome.sockets.udp.close(a),!1):!0};chrome.sockets.udp.create({},function(a){var d=a.socketId;console.log("[create] socketInfo",a);status("binding 0.0.0.0");chrome.sockets.udp.bind(d,"0.0.0.0",0,function(a){console.log("[bind] result",
a);if(!f(d,"bind",a))return!1;status("enabling broadcast");chrome.sockets.udp.setBroadcast(d,!0,function(a){console.log("[setBroadcast] result",a);if(!f(d,"broadcast",a))return!1;status("sending to "+b+":"+c);chrome.sockets.udp.send(d,e,b,c,function(a){console.log("[send] sendInfo",a);if(!f(d,"send",a.resultCode))return!1;status("closing");chrome.sockets.udp.close(d,function(){status("sent to "+b+":"+c);store_settings()})})})})});return!1}
function sync_it(a){var b=$$("span[name="+a+"-many]");$$("span[name="+a+"-one]");if(b.hidden){var c=$$("input[name="+a+"]");b=c.value.split(":");if(6!=b.length){b=c.value.replace(/[ :]/g,"");if(12!=b.length)return status("invalid "+a+"; please fix"),!1;b=b.match(/../g)}else for(c=0;6>c;++c)if(2<b[c].length)return status("invalid "+a+" please fix"),!1;for(c=0;6>c;++c)$$("input[name="+a+c+"]").value=b[c]}else{b="";for(c=0;6>c;++c)b+=$$("input[name="+a+c+"]").value,5>c&&(b+=":");$$("input[name="+a+"]").value=
b}}function sync_mac(){return sync_it("mac")}function sync_pass(){return sync_it("pass")}function paste_mac(){sync_mac();var a=$$("span[name=mac-many]"),b=$$("span[name=mac-one]");a.hidden=!a.hidden;b.hidden=!b.hidden;return!1}function paste_pass(){sync_pass();var a=$$("span[name=pass-many]"),b=$$("span[name=pass-one]");a.hidden=!a.hidden;b.hidden=!b.hidden;return!1}
var computers=[],settings_keys=["computers","last_selected","theme"],old_settings_keys=["host","mac","pass","port"],default_name="Default",default_host="192.168.0.255",default_port="40000",default_mac="20:00:00:00:00:00",default_pass="00:00:00:00:00:00";
function load_computer(a){var b=computers[a]||{};chrome.storage.local.set({last_selected:a});a=$$("form[name=settings]");a.computer.value=b.name||default_name;a.host.value=b.host||default_host;a.port.value=b.port||default_port;paste_mac();a.mac.value=b.mac||default_mac;paste_mac();paste_pass();a.pass.value=b.pass||default_pass;paste_pass()}
function load_settings(){chrome.storage.local.get(settings_keys,function(a){"computers"in a?(computers=a.computers||[],populate_computers(),load_computer(a.last_selected||0)):chrome.storage.local.get(old_settings_keys,function(a){computers[0]=a;populate_computers();load_computer(0);store_settings();chrome.storage.local.remove(old_settings_keys)})})}
function store_settings(){sync_mac();sync_pass();var a=$$("form[name=settings]"),b=$$("select[name=computer]").selectedIndex;computers[b]={name:a.computer.value,host:a.host.value,mac:a.mac.value,pass:a.pass.value,port:a.port.value};chrome.storage.local.set({computers})}function toggle_theme(){const a="light"==get_css_var("theme")?"dark":"light";$$("link#theme-override").href=`css/${a}.css`;chrome.storage.local.set({theme:a})}
function check_empty_computers(a){if(0==a.length){var b=document.createElement("option");b.text="Default";a.add(b,0);load_computer(0)}}function populate_computers(){for(var a=$$("select[name=computer]"),b=a.length=0;b<computers.length;b++){var c=document.createElement("option");c.text=(computers[b]||{}).name||default_name;a.add(c,b)}check_empty_computers(a)}function select_computer(){load_computer($$("select[name=computer]").selectedIndex)}
function toggle_add_fields(a,b){a.disabled=!0;a.style.display="none";b.disabled=!1;b.style.display="inline";b.focus()}function del_computer(){var a=$$("select[name=computer]"),b=a.selectedIndex;computers.splice(b,1);a.remove(b);check_empty_computers(a);b==a.length&&0<b&&--b;load_computer(b);store_settings()}function add_computer_start(){var a=$$("select[name=computer]"),b=$$("input[name=computer_name]");"none"==a.style.display?add_computer():toggle_add_fields(a,b)}
function add_computer_check(a){"Enter"==a.key&&(add_computer(),a.preventDefault())}
function add_computer(){var a=$$("select[name=computer]");$$("form[name=settings]");var b=$$("input[name=computer_name]"),c=b.value.trim();if(""==c)b.value="",toggle_add_fields(b,a);else{for(var d=0;d<a.length;++d)if(a.options[d].value==c){popup_msg(b,"ERROR: computer name already exists!");return}b.value="";d=document.createElement("option");d.text=c;a.add(d,-1);computers[a.length-1]={name:c};load_computer(a.length-1);toggle_add_fields(b,a);store_settings()}}
window.onload=function(){$$("input[name=send]").onclick=send;$$("select[name=computer]").onchange=select_computer;$$("a[name=mac-paste]").onclick=paste_mac;$$("a[name=pass-paste]").onclick=paste_pass;$$("input[name=del_computer]").onclick=del_computer;$$("input[name=add_computer]").onclick=add_computer_start;$$("input[name=computer_name]").onkeypress=add_computer_check;$$("button[name=theme]").onclick=toggle_theme;load_settings()};
